// Copyright 2018 Espressif Systems (Shanghai) PTE LTD
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
#ifndef __OTA_TIMER_HANDLER_H__
#define __OTA_TIMER_HANDLER_H__

#ifdef __cplusplus
extern "C" {
#endif

/*--OTA 中可以利用的定时器ID的范围(0~69)------------------------*/
enum custom_ota_timer_id {
    TID_GT_TIMER_NULL = 0,

	//reload timer
	TID_GT_TIMER_RELOAD_BASE,
    TID_GT_MAIN_TIMER=TID_GT_TIMER_RELOAD_BASE,

	TID_GT_RELOAD_TEST_TIMER,

	//add reload timer above
	TID_GT_TIMER_RELOAD_MAX,


	//once timer
	TID_GT_TIMER_ONCE_BASE,
    TID_GT_TIMER_HEART=TID_GT_TIMER_ONCE_BASE,
    TID_GT_TIMER_HEART_REPLY_CHECK,

    TID_GT_TIMER_UNMOUNT_REPLY_CHECK,
    TID_GT_TIMER_OPENCOVER_REPLY_CHECK,
    TID_GT_TIMER_SOS_REPLY_CHECK,
    TID_GT_TIMER_OPENBOX_REPLY_CHECK,
    TID_GT_TIMER_FREEFALL_REPLY_CHECK,
    TID_GT_TIMER_LOW_BATTERY_REPLY_CHECK,
    TID_GT_TIMER_LOW_BATTERY_PRESET_REPLY_CHECK, // 10
    TID_GT_TIMER_HIGH_TEMP_REPLY_CHECK,
    TID_GT_TIMER_MOTION_REPLY_CHECK,
    TID_GT_TIMER_COLLISION_REPLY_CHECK,
    TID_GT_TIMER_TILT_REPLY_CHECK,
    TID_GT_TIMER_USB_CHARGING_REPLY_CHECK,
    TID_GT_TIMER_USB_CHANGE_REMOVE_REPLY_CHECK,
    TID_GT_TIMER_GFENCE_IN_REPLY_CHECK,
    TID_GT_TIMER_GFENCE_OUT_REPLY_CHECK,
    TID_GT_TIMER_ACC_ON_REPLY_CHECK,
    TID_GT_TIMER_ACC_OFF_REPLY_CHECK,   //20
    TID_GT_TIMER_IDLE_ON_REPLY_CHECK,
    TID_GT_TIMER_IDLE_OFF_REPLY_CHECK,
    TID_GT_TIMER_POWERON_REPLY_CHECK,
    TID_GT_TIMER_UNMOUNT_REC_REPLY_CHECK,
    TID_GT_TIMER_OPENCOVER_REC_REPLY_CHECK,
    TID_GT_TIMER_OPENBOX_REC_REPLY_CHECK,
    TID_GT_TIMER_FREEFALL_REC_REPLY_CHECK,
    TID_GT_TIMER_HIGH_TEMP_REC_REPLY_CHECK,
    TID_GT_TIMER_MOTION_REC_REPLY_CHECK,
    TID_GT_TIMER_COLLISION_REC_REPLY_CHECK, //30
    TID_GT_TIMER_TILT_REC_REPLY_CHECK,
    TID_GT_TIMER_POWEROFF_REPLY_CHECK,
    TID_GT_TIMER_LOW_TEMP_REPLY_CHECK,
    TID_GT_TIMER_LOW_TEMP_REC_REPLY_CHECK,

    TID_GT_TIMER_DIN1_ON_REPLY_CHECK,
    TID_GT_TIMER_DIN2_ON_REPLY_CHECK,
    TID_GT_TIMER_DIN3_ON_REPLY_CHECK,
    TID_GT_TIMER_DIN4_ON_REPLY_CHECK,
    TID_GT_TIMER_DIN5_ON_REPLY_CHECK,
    TID_GT_TIMER_DIN6_ON_REPLY_CHECK,  // 40
    TID_GT_TIMER_DIN7_ON_REPLY_CHECK,
    TID_GT_TIMER_ADC1_INC_REPLY_CHECK,
    TID_GT_TIMER_ADC1_DEC_REPLY_CHECK,
    TID_GT_TIMER_ADC2_INC_REPLY_CHECK,
    TID_GT_TIMER_ADC2_DEC_REPLY_CHECK,
    TID_GT_TIMER_ADC3_INC_REPLY_CHECK,
    TID_GT_TIMER_ADC3_DEC_REPLY_CHECK,
    TID_GT_TIMER_DIN1_OFF_REPLY_CHECK,
    TID_GT_TIMER_DIN2_OFF_REPLY_CHECK,
    TID_GT_TIMER_DIN3_OFF_REPLY_CHECK, // 50
    TID_GT_TIMER_DIN4_OFF_REPLY_CHECK,
    TID_GT_TIMER_DIN5_OFF_REPLY_CHECK,
    TID_GT_TIMER_DIN6_OFF_REPLY_CHECK,
    TID_GT_TIMER_DIN7_OFF_REPLY_CHECK,
    TID_GT_TIMER_ADC1_INC_REC_REPLY_CHECK,
    TID_GT_TIMER_ADC1_DEC_REC_REPLY_CHECK,
    TID_GT_TIMER_ADC2_INC_REC_REPLY_CHECK,
    TID_GT_TIMER_ADC2_DEC_REC_REPLY_CHECK,
    TID_GT_TIMER_ADC3_INC_REC_REPLY_CHECK,
    TID_GT_TIMER_ADC3_DEC_REC_REPLY_CHECK, // 60
    TID_GT_TIMER_HIGH_SPEED_REPLY_CHECK,
    TID_GT_TIMER_HIGH_SPEED_REC_REPLY_CHECK,
    TID_GT_TIMER_EXTERNAL_POWER_LOWER_REPLY_CHECK,
    TID_GT_TIMER_CUT_12V_REPLY_CHECK,
    TID_GT_TIMER_RECOVER_12V_REPLY_CHECK,
    TID_GT_TIMER_GOOGLE_REPLY_CHECK,
    TID_GT_TIMER_VIBRATION_REPLY_CHECK,
    TID_GT_TIMER_DRAG_REPLY_CHECK,
    TID_GT_TIMER_ANTITHEFT_REPLY_CHECK,
    TID_GT_TIMER_JAMMERD_ENTER_REPLY_CHECK,// 70
    TID_GT_TIMER_JAMMERD_EXIT_REPLY_CHECK,

    // 20-3
    TID_GT_TIMER_LOGIN_WAIT,
    TID_GT_TIMER_SETGETTING_WAIT,
    TID_GT_TIMER_CMD_DISCONNECT,
    TID_GT_TIMER_STOP_SMS_FORWARD,
    TID_GT_TIMER_UPGRADE_CMD_WAIT,
    TID_GT_TIMER_UPGRADE_CMD_OVERTIME,
    TID_GT_TIMER_UPGRADE_CMD_SUCCESS,

    // 30-3
    TID_GT_TIMER_LOCK_SERVER,
    TID_GT_TIMER_LED_TURN_OFF, // 80

    TID_GT_TIMER_IP2_LOGIN_WAIT,
    TID_GT_TIMER_IP2_SETGETTING_WAIT,
    TID_GT_TIMER_IP2_HEART_REPLY_CHECK,
    TID_GT_TIMER_SHORT_LINK_IP1_DISCON_SOCKET,
    TID_GT_TIMER_SHORT_LINK_IP2_DISCON_SOCKET,
    TID_GT_TIMER_CHECK_OTA_FILE_OK,

    //50-3
    TID_GT_TIMER_HOST_AUTH,
    TID_GT_TIMER_SHORT_LINK_IP1_TIMEOUT,
    TID_GT_TIMER_SHORT_LINK_IP2_TIMEOUT,
    TID_GT_TIMER_GOOGLE_ADDR_REQUEST_TIMEOUT,  // 90
    TID_GT_TIMER_SEND_DRIVING_ACCIDENT,
    TID_GT_TIMER_AGPS_LOCATION_REQ_TIMEOUT,
    // 60-3
    TID_GT_TIMER_FACTORYTEST_TIMEOUT,
    TID_GT_TIMER_COMMON_DATA_SEND ,
    TID_GT_TIMER_USSD_CALL,
    TID_GT_TIMER_TOPFLY_CONN_TIMEOUT,
    TID_GT_TIMER_TOPFLY2_CONN_TIMEOUT,
    TID_GT_TIMER_IP3_CONN_TIMEOUT,
    TID_GT_TIMER_ADDR_CONN_TIMEOUT,
    TID_GT_TIMER_SEND_ADDR, // 100
    TID_GT_TIMER_MOVE_UPGRADE_OTA,

    // 70-3
    TID_GT_TIMER_CLOSE_TOPFLY2,
    TID_GT_TIMER_SOCKET_ACK_TIMEOUT,
    TID_GT_TIMER_SOCKET2_ACK_TIMEOUT,
    TID_GT_TIMER_OTA_OK_TIMER,
    TID_GT_TIMER_UPGRADE_DIRECTLY,
#ifdef __OTA_OBD_SUPPORT__
    TID_GT_TIMER_OBDEX_CMD,
#endif
    TID_GT_TIMER_GPS_ACCON,
    TID_GT_TIMER_0x81_CMD_HANDLER ,
#ifdef __OTA_MODEM_SUPPORT__
    TID_GT_TIMER_REQ_CSQ_LOOP, // 110
    TID_GT_TIMER_PDP_INIT,

    // 80-3
    TID_GT_TIMER_REQ_GATT_LOOP,
    TID_GT_TIMER_UPGRADE_INTERNAL,
    TID_GT_TIMER_TALK_TO_MCU,
#endif // __OTA_MODEM_SUPPORT__
#ifdef  __OTA_UT_SUPPORT__
    TID_GT_TIMER_GPIO_DELAY,
#endif /*__OTA_UT_SUPPORT__*/
    TID_GT_TIMER_CLEAR_CURR_CMD,
    TID_GT_TIMER_SET_NW_PARAM,
    TID_GT_TIMER_LOW_POWER_ENTER,
    TID_GT_TIMER_SYNC_TIMEOUT,
    TID_GT_TIMER_MCURESET,
    TID_GT_TIMER_POWEROFF_ENTER,  //120
    TID_GT_TIMER_LOW_POWER,
    TID_GT_TIMER_CLOSE_SOCKET_REBOOT_DELAY,
    TID_GT_TIMER_MCU_DATA_QUERY,
    TID_GT_TIMER_PARSE_BATCHSET,
    TID_GT_TIMER_ALL_FUNC_OPEN,
#ifdef __OTA_BT_UL_SUPPORT__
    TID_GT_TIMER_BTSPP_TIMEOUT,
#endif
    TID_GT_TIMER_RLYMODE3,
    TID_GT_TIMER_ACCIDENT_POST,
#ifdef __L76_GPS__
    TID_GT_TIMER_EPOTIMER,
    TID_GT_TIMER_DAY_TIMER, // 130
    TID_GT_TIMER_EPO_DL_TIMER,
#endif
    TID_GT_TIMER_BT_SEND_HANDLE,
    TID_GT_TIMER_FOR_TIME_VALID,
    TID_GT_TIMER_FILE_DOWNLOAD_TIMEOUT,
    TID_GT_TIMER_GPS_DLD,
    TID_GT_TIMER_GET_UPLOADTIMER,
    TID_GT_TIMER_UPDATE_MCU_TIMEOUT,
    TID_GT_TIMER_SHUTDOWN_DELAY,
    TID_GT_TIMER_WAIT_FOR_USER_CMD,
    TID_GT_TIMER_MCU_HBT, // 140
    TID_GT_TIMER_BTRELAY_TIMER,
    TID_GT_TIMER_NVRAM_SAVE_EXEC,
    TID_GT_TIMER_RTINF_SAVE_EXEC,
    TID_GT_TIMER_CHECK_BADB_STATE,
    TID_GT_TIMER_SHORT_STOP_REPLY_CHECK,
    TID_GT_TIMER_OBD_UPGRADING_CHECK,

	//add once timer above
	TID_GT_TIMER_ONCE_MAX,
};
#define Sec2MSec(sec)   ((sec)*1000)
#define MSec2USec(msec) ((msec)*1000)
#define Sec2USec(sec)   (Sec2MSec(MSec2USec(sec)))
#define Min2Sec(min)    ((min)*60)
#define Min2MSec(min)   (Sec2MSec(Min2Sec(min)))

void ota_timer_handler_init(void);

#ifdef __cplusplus
}
#endif

#endif
